spring:
  datasource:
    "url": "jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl"
    "driver-class-name": "oracle.jdbc.OracleDriver"
    "username": "rm557598"
    "password": "040903"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    "path": "/swagger-ui.html"
  api-docs:
    "path": "/v3/api-docs"
